baseURL = "https://hulecom.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Hugo Lecomte"
theme = "minimal"
disqusShortname = "hulecom" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Hugo Lecomte"
    description = "Personal Reasearch page"
    githubUsername = "hulecom"
    accent = "#379683"
    profilePic = "/20190710_115618.jpg"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    post = "PhD student at [ITES](https://ites.unistra.fr/), University of Strasbourg"
    address = "5 rue Ren√© Descartes, 67000 Strasbourg, France"
    mail = "[hlecomte (at) unistra.fr](mailto:hlecomte@unistra.fr)"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/research/"
    name = "My research"
    weight = 2

[[menu.main]]
    url = "/publications/"
    name = "Publications"
    weight = 3

[[menu.main]]
    url = "/conferences/"
    name = "Conferences"
    weight = 4

[[menu.main]]
    url = "/teaching/"
    name = "Teaching"
    weight = 5

[[menu.main]]
    url = "/cv/"
    name = "CV"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:hlecomte@unistra.fr"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/hulecom/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://scholar.google.fr/citations?user=tGrXnO4AAAAJ"
    name = "fas fa-graduation-cap"
    weight = 3

[[menu.icon]]
    url = "https://www.researchgate.net/profile/Hugo_Lecomte2"
    name = "fab fa-researchgate"
    weight = 4

[[menu.icon]]
    url = "https://twitter.com/HuLecomte/"
    name = "fab fa-twitter"
    weight = 5
